
-- @block
DROP TABLE IF EXISTS PATIENTS;
DROP TABLE IF EXISTS MEDICAL_HISTORY;
DROP TABLE IF EXISTS MEDICAL_PROCEDURES;
DROP TABLE IF EXISTS MEDICAL_DEPARTMENTS;
DROP TABLE IF EXISTS MEDICAL_LOCATIONS;


-- @block
CREATE TABLE PATIENTS (
  PATIENT_ID CHAR(9) NOT NULL,
  FIRST_NAME VARCHAR(15) NOT NULL,
  LAST_NAME VARCHAR(15) NOT NULL,
  SSN CHAR(9),
  BIRTH_DATE DATE,
  SEX CHAR,
  ADDRESS VARCHAR(30),
  DEPT_ID CHAR(9) NOT NULL,
  PRIMARY KEY (PATIENT_ID)
);

-- @block
CREATE TABLE MEDICAL_HISTORY (
  MEDICAL_HISTORY_ID CHAR(9) NOT NULL,
  PATIENT_ID CHAR(9) NOT NULL,
  DIAGNOSIS_DATE DATE,
  DIAGNOSIS_CODE VARCHAR(10),
  MEDICAL_CONDITION VARCHAR(100),
  DEPT_ID CHAR(9),
  PRIMARY KEY (MEDICAL_HISTORY_ID)
);

-- @block
CREATE TABLE MEDICAL_PROCEDURES (
  PROCEDURE_ID CHAR(9) NOT NULL,
  PROCEDURE_NAME VARCHAR(30),
  PROCEDURE_DATE DATE,
  PATIENT_ID CHAR(9) NOT NULL,
  DEPT_ID CHAR(9),
  PRIMARY KEY (PROCEDURE_ID)
);

-- @block
CREATE TABLE MEDICAL_DEPARTMENTS (
  DEPT_ID CHAR(9) NOT NULL,
  DEPT_NAME VARCHAR(50),
  MANAGER_ID CHAR(9),
  LOCATION_ID CHAR(9),
  PRIMARY KEY (DEPT_ID)
);

-- @block
CREATE TABLE MEDICAL_LOCATIONS (
  LOCATION_ID CHAR(9) NOT NULL,
  DEPT_ID CHAR(9) NOT NULL,
  LOCATION_NAME VARCHAR(50),
  PRIMARY KEY (LOCATION_ID, DEPT_ID)
);

-- @block
INSERT INTO patients (
  PATIENT_ID,
  FIRST_NAME,
  LAST_NAME,
  SSN,
  BIRTH_DATE,
  SEX,
  ADDRESS,
  DEPT_ID
)
VALUES 
  ('P001','John','Doe','123456789','1990-05-15','M','123 Main St','D001'),
  ('P002','Jane','Smith','987654321','1985-10-20','F','456 Oak Ave','D002'),
  ('P003','Michael','Johnson','111222333','1975-03-12','M','789 Elm St','D003'),
  ('P004','Emily','Brown','444555666','1980-09-25','F','321 Pine Rd','D004'),
  ('P005','William','Miller','777888999','1992-11-18','M','567 Maple Ave','D003')
;

-- @block
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/MEDICAL_PROCEDURES.csv'
INTO TABLE medical_procedures
FIELDS TERMINATED BY ',';

-- @block
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/MEDICAL_PROCEDURES.csv'
INTO TABLE medical_procedures
FIELDS TERMINATED BY ',';

-- @block
SHOW VARIABLES LIKE "secure_file_priv";